[toolchain]
channel = "nightly"

[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tsrc/arch/riscv/link.x",
    "-C", "code-model=medium",
]
runner = "qemu-system-riscv64 -s -machine virt -bios opensbi_v1.7.bin -serial stdio -smp cores=4 -kernel"
